<?php
  $params_google_map_positions = array( 
                                        ''                              =>  '',
                                        'TOP_LEFT'                      =>  'TOP_LEFT',
                                        'TOP_CENTER'                    =>  'TOP_CENTER',
                                        'TOP_RIGHT'                     =>  'TOP_RIGHT',
                                        'LEFT_TOP'                      =>  'LEFT_TOP',
                                        'RIGHT_TOP'                     =>  'RIGHT_TOP',
                                        'LEFT_CENTER'                   =>  'LEFT_CENTER',
                                        'RIGHT_CENTER'                  =>  'RIGHT_CENTER',
                                        'LEFT_BOTTOM'                   =>  'LEFT_BOTTOM',
                                        'RIGHT_BOTTOM'                  =>  'RIGHT_BOTTOM',
                                        'BOTTOM_CENTER'                 =>  'BOTTOM_CENTER',
                                        'BOTTOM_LEFT'                   =>  'BOTTOM_LEFT',
                                        'BOTTOM_RIGHT'                  =>  'BOTTOM_RIGHT',
                                          );

  $params = array( 
              'name',
              array(
                "type"          =>  "encoded_text",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'API Key', 'vc_cfb' ),
                "param_name"    =>  "api_key",
                "value"         =>  '',
                "description"   =>  '<a href="http://console.developers.google.com" target="_blank">Google API</a>',
                "group"         =>  __( 'General', 'vc_cfb' )
              ),
              'label',
              array(
                'type'          => 'checkbox',
                'value'         =>  'false',
                'class'         => 'vc_cfb_hide_field',
                'heading'       => __( 'Show map?', 'vc_cfb' ),
                'param_name'    => 'map',
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              'placeholder',
              'tab',
              'required',
              'autofocus',
              'readonly',
              array(
                "type"          =>  "encoded_text",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Default Location: latitude', 'vc_cfb' ),
                "param_name"    =>  "latitude",
                "value"         =>  '',
                "description"   =>  __( "Value with '<strong>,</strong>' delimiter", 'vc_cfb' ),
                "group"         =>  __( 'General', 'vc_cfb' )
              ),
              array(
                "type"          =>  "encoded_text",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Default Location: longitude', 'vc_cfb' ),
                "param_name"    =>  "longitude",
                "value"         =>  '',
                "description"   =>  __( "Value with '<strong>,</strong>' delimiter", 'vc_cfb' ),
                "group"         =>  __( 'General', 'vc_cfb' )
              ),
              array(
                'type'          => 'checkbox',
                'value'         =>  'false',
                'class'         => 'vc_cfb_hide_field',
                'heading'       => __( 'Show map on mobile devices?', 'vc_cfb' ),
                'param_name'    => 'mobile',
                "dependency"    =>  array( 'element' => 'map', 'value' => 'true' ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                "type"          =>  "checkbox",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Enable draggable marker?', 'vc_cfb' ),
                "param_name"    =>  "map_draggable",
                "value"         =>  'false',
                "description"   =>  __( 'A draggable marker to redefine the position.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'map', 'value' => 'true' ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Map height', 'vc_cfb' ),
                "param_name"    =>  "map_height",
                "value"         =>  '300px',
                "dependency"    =>  array( 'element' => 'map', 'value' => 'true' ),
                "description"   =>  '',
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Country limit', 'vc_cfb' ),
                "param_name"    =>  "map_country",
                "value"         =>  '',
                "dependency"    =>  array( 'element' => 'map', 'value' => 'true' ),
                "description"   =>  __( 'Show elements only for this country. For example: <code>de</code>. If empty - disabled.', 'vc_cfb' ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Language for map', 'vc_cfb' ),
                "param_name"    =>  "language",
                "value"         =>  array( 
                                        ''                        =>  '',
                                        'العربية'                     => 'ar', 
                                        'বাংলা'                      => 'bn', 
                                        'Български'                   => 'bg', 
                                        'Català'                      => 'ca', 
                                        'Čeština'                     => 'cs', 
                                        'Dansk'                       => 'da', 
                                        'Deutsch'                     => 'de',
                                        'Ελληνικά'                    => 'el', 
                                        'English (US)'                => 'en', 
                                        'English (Australian)'        =>  'en-AU',
                                        'English (UK)'                =>  'en-GB',
                                        'Español'                     => 'es', 
                                        'Euskara'                     =>  'eu',
                                        'فارسی'                       => 'fa', 
                                        'Suomi'                       => 'fi', 
                                        'Filipino'                    => 'fil', 
                                        'Français'                    => 'fr', 
                                        'Galego'                      =>  'gl',
                                        'ગુજરાતી'                      => 'gu',
                                        'हिन्दी'                     => 'hi', 
                                        'Hrvatski'                    => 'hr', 
                                        'Magyar'                      => 'hu', 
                                        'Bahasa Indonesia'            => 'id', 
                                        'Italiano'                    => 'it',
                                        'עברית'                       => 'iw', 
                                        '日本語'                       => 'ja', 
                                        'ಕನ್ನಡ'                      => 'kn',
                                        '한국어'                        => 'ko', 
                                        'Lietuvių'                    => 'lt', 
                                        'Latviešu'                    => 'lv',
                                        'മലയാളം'                     => 'ml', 
                                        'मराठी'                       => 'mr',
                                        'Nederlands'                  => 'nl', 
                                        'Norsk'                       => 'no',
                                        'Polski'                      => 'pl',
                                        'Português'                   => 'pt', 
                                        'Português brasileiro'        => 'pt-BR', 
                                        'Português (Português)'       => 'pt-PT', 
                                        'Română'                      => 'ro', 
                                        'Русский'                     => 'ru', 
                                        'Slovenčina'                  => 'sk',
                                        'Slovenščina'                 => 'sl', 
                                        'Српски / srpski'             => 'sr', 
                                        'Svenska'                     => 'sv', 
                                        'தமிழ்'                      => 'ta', 
                                        'తెలుగు'                    => 'te', 
                                        'ภาษาไทย'                     => 'th', 
                                        'Tagalog'                     =>  'tl',
                                        'Türkçe'                      => 'tr', 
                                        'Українська мова'             => 'uk',
                                        'Tiếng Việt'                  => 'vi',
                                        '简体中文'                     => 'zh-CN', 
                                        '繁體中文'                     => 'zh-TW', 
                                          ),
                "description"   =>  __( 'If field empty, language will be autodetected.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'map', 'value' => 'true' ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Show panControl on map', 'vc_cfb' ),
                "param_name"    =>  "map_pancontrol_posistion",
                "value"         =>  $params_google_map_positions,
                "description"   =>  __( 'Displays buttons for panning the map.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'map', 'value' => 'true' ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Show zoomControl on map', 'vc_cfb' ),
                "param_name"    =>  "map_zoomcontrol_posistion",
                "value"         =>  $params_google_map_positions,
                "description"   =>  __( 'Displays a slider (for large maps) or small "+/-" buttons (for small maps) to control the zoom level of the map.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'map', 'value' => 'true' ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Size of zoomControl', 'vc_cfb' ),
                "param_name"    =>  "map_zoomcontrol_size",
                "value"         =>  array( 
                                        'auto detect'              =>  '',
                                        'small'                    =>  'SMALL',
                                        'large'                    =>  'LARGE',
                                          ),
                "description"   =>  '',
                "dependency"    =>  array( 'element' => 'map_zoomcontrol_posistion', 'value' => array( 'TOP_LEFT', 'TOP_CENTER', 'TOP_RIGHT', 'LEFT_TOP', 'RIGHT_TOP', 'LEFT_CENTER', 'RIGHT_CENTER', 'LEFT_BOTTOM', 'RIGHT_BOTTOM', 'BOTTOM_CENTER', 'BOTTOM_LEFT', 'BOTTOM_RIGHT' ) ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Show streetViewControl on map', 'vc_cfb' ),
                "param_name"    =>  "map_streetviewcontrol_posistion",
                "value"         =>  $params_google_map_positions,
                "description"   =>  __( 'Contains a Pegman icon which can be dragged onto the map to enable Street View.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'map', 'value' => 'true' ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Show rotateControl on map', 'vc_cfb' ),
                "param_name"    =>  "map_rotatecontrol_posistion",
                "value"         =>  $params_google_map_positions,
                "description"   =>  __( 'Enables/disables the appearance of a Rotate control for controlling the orientation of 45&deg; imagery.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'map', 'value' => 'true' ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                'type'          => 'checkbox',
                'value'         =>  'false',
                'class'         => 'vc_cfb_hide_field',
                'heading'       => __( 'Show scaleControl on map?', 'vc_cfb' ),
                'param_name'    => 'map_scalecontrol',
                "dependency"    =>  array( 'element' => 'map', 'value' => 'true' ),
                "description"   =>  __( 'Displays a map scale element.', 'vc_cfb' ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Show mapTypeControl on map', 'vc_cfb' ),
                "param_name"    =>  "map_maptypecontrol_posistion",
                "value"         =>  $params_google_map_positions,
                "description"   =>  __( 'Enables/disables the Map Type control that lets the user toggle between map types (such as Map and Satellite).', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'map', 'value' => 'true' ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Style of mapTypeControl', 'vc_cfb' ),
                "param_name"    =>  "map_maptypecontrol_style",
                "value"         =>  array( 
                                        'DEFAULT'                       =>  'DEFAULT',
                                        'HORIZONTAL_BAR'                =>  'HORIZONTAL_BAR',
                                        'DROPDOWN_MENU'                 =>  'DROPDOWN_MENU',
                                          ),
                "description"   =>  '',
                "dependency"    =>  array( 'element' => 'map_maptypecontrol_posistion', 'value' => array( 'TOP_LEFT', 'TOP_CENTER', 'TOP_RIGHT', 'LEFT_TOP', 'RIGHT_TOP', 'LEFT_CENTER', 'RIGHT_CENTER', 'LEFT_BOTTOM', 'RIGHT_BOTTOM', 'BOTTOM_CENTER', 'BOTTOM_LEFT', 'BOTTOM_RIGHT' ) ),
                "group"         =>  __( 'Map', 'vc_cfb' )
              ),
              'label_position',
              'label_width',
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Size', 'vc_cfb' ),
                "param_name"    =>  "size",
                "value"         =>  '',
                "description"   =>  __( 'The size attribute specifies the visible width, in characters. It can be rewrited on css. If value is empty, then option will be disabled.', 'vc_cfb' ),
                "group"         =>  __( 'Design', 'vc_cfb' )
              ),
              'add_icon',
              'icon_align',
              'icon_type',
              'icon_fa',
              'icon_oi',
              'icon_ti',
              'icon_ei',
              'icon_li',
              'icon_color',
              'id',
              'classes',
              );