<?php
  $params = array( 
              array(
                "type"          =>  "custom_title",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  '',
                "param_name"    =>  "custom_title",
                "value"         =>  '',
                "description"   =>  __( 'We are reccomend to use only one reCAPTCHA 2.0 per page with ajax forms.', 'vc_cfb' ),
                "group"         =>  __( 'General', 'vc_cfb' )
              ),
              'name',
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Key', 'vc_cfb' ),
                "param_name"    =>  "key",
                "value"         =>  '',
                "description"   =>  sprintf( __( 'Will be embed to HTML code. Click <a href="%s" target="_blank">here</a> to get key.', 'vc_cfb' ), 'https://www.google.com/recaptcha/admin' ),
                "group"         =>  __( 'General', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Secret key', 'vc_cfb' ),
                "param_name"    =>  "secret_key",
                "value"         =>  '',
                "description"   =>  sprintf( __( 'This key are using for communication between your site and Google. Be sure to keep it a secret. Click <a href="%s" target="_blank">here</a> to get key.', 'vc_cfb' ), 'https://www.google.com/recaptcha/admin' ),
                "group"         =>  __( 'General', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Type', 'vc_cfb' ),
                "param_name"    =>  "type",
                "value"         =>  array( __( 'image', 'vc_cfb' ) => 'image', __( 'audio', 'vc_cfb' ) => 'audio' ),
                "description"   =>  __( 'The type of CAPTCHA to serve.', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              'tab',
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Language', 'vc_cfb' ),
                "param_name"    =>  "hl",
                "value"         =>  array( 
                                        '' =>  '',
                                        'العربية'                     => 'ar', 
                                        'বাংলা'                      => 'bn', 
                                        'Български'                   => 'bg', 
                                        'Català'                      => 'ca', 
                                        '简体中文'                     => 'zh-CN', 
                                        '繁體中文'                     => 'zh-TW', 
                                        'Hrvatski'                    => 'hr', 
                                        'Čeština'                     => 'cs', 
                                        'Dansk'                       => 'da', 
                                        'Nederlands'                  => 'nl', 
                                        'English (UK)'                => 'en-GB', 
                                        'English (US)'                => 'en', 
                                        'Eesti'                       => 'et', 
                                        'Filipino'                    => 'fil', 
                                        'Suomi'                       => 'fi', 
                                        'Français'                    => 'fr', 
                                        'Français canadien'           => 'fr-CA', 
                                        'Deutsch'                     => 'de', 
                                        'ગુજરાતી'                      => 'gu', 
                                        'Österreichisches Deutsch'    => 'de-AT', 
                                        'Schweizerdeutsch'            => 'de-CH', 
                                        'Ελληνικά'                    => 'el', 
                                        'עברית'                       => 'iw', 
                                        'हिन्दी'                     => 'hi', 
                                        'Magyar'                      => 'hu', 
                                        'Bahasa Indonesia'            => 'id', 
                                        'Italiano'                    => 'it', 
                                        '日本語'                       => 'ja', 
                                        'ಕನ್ನಡ'                      => 'kn', 
                                        '한국어'                        => 'ko', 
                                        'Latviešu'                    => 'lv', 
                                        'Lietuvių'                    => 'lt', 
                                        'Bahasa Melayu'               => 'ms', 
                                        'മലയാളം'                     => 'ml', 
                                        'मराठी'                       => 'mr', 
                                        'Norsk'                       => 'no', 
                                        'فارسی'                       => 'fa', 
                                        'Polski'                      => 'pl', 
                                        'Português'                   => 'pt', 
                                        'Português brasileiro'        => 'pt-BR', 
                                        'Português (Português)'       => 'pt-PT', 
                                        'Română'                      => 'ro', 
                                        'Русский'                     => 'ru', 
                                        'Српски / srpski'             => 'sr', 
                                        'Slovenčina'                  => 'sk', 
                                        'Slovenščina'                 => 'sl', 
                                        'Español'                     => 'es', 
                                        'Español latinoamericano'     => 'es-419', 
                                        'Svenska'                     => 'sv', 
                                        'தமிழ்'                      => 'ta', 
                                        'తెలుగు'                    => 'te', 
                                        'ภาษาไทย'                     => 'th', 
                                        'Türkçe'                      => 'tr', 
                                        'Українська мова'             => 'uk', 
                                        'اردو'                        => 'ur', 
                                        'Tiếng Việt'                  => 'vi' 
                                          ),
                "description"   =>  __( 'Auto-detects the user\'s language if unspecified. Will be used language of the first element on the page for each other reCaptha.', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Theme', 'vc_cfb' ),
                "param_name"    =>  "theme",
                "value"         =>  array( __( 'light', 'vc_cfb' ) => 'light', __( 'dark', 'vc_cfb' ) => 'dark' ),
                "description"   =>  __( 'The color theme of the widget.', 'vc_cfb' ),
                "group"         =>  __( 'Design', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Size', 'vc_cfb' ),
                "param_name"    =>  "size",
                "value"         =>  array( __( 'normal', 'vc_cfb' ) => 'normal', __( 'compact', 'vc_cfb' ) => 'compact' ),
                "description"   =>  __( 'The size of the widget.', 'vc_cfb' ),
                "group"         =>  __( 'Design', 'vc_cfb' )
              ),
              'classes'
            );