<?php
  $params = array( 
              'name',
              'label',
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "is_html5"      =>  true,
                "heading"       =>  __( 'Type of Field', 'vc_cfb' ),
                "param_name"    =>  "input_type",
                "value"         =>  array( 
                                            __( 'Text', 'vc_cfb' )                                                        => 'text', 
                                            __( 'Password', 'vc_cfb' )                                                    => 'password', 
                                            __( 'Color', 'vc_cfb' )                                                       => 'color', 
                                            __( 'Date', 'vc_cfb' )                                                        => 'date', 
                                            __( 'Datetime', 'vc_cfb' )                                                    => 'datetime', 
                                            __( 'Datetime-local', 'vc_cfb' )                                              => 'datetime-local', 
                                            __( 'Email', 'vc_cfb' )                                                       => 'email', 
                                            __( 'Number', 'vc_cfb' )                                                      => 'number', 
                                            __( 'Range', 'vc_cfb' )                                                       => 'range', 
                                            __( 'Search', 'vc_cfb' )                                                      => 'search', 
                                            __( 'Telephone', 'vc_cfb' )                                                   => 'tel', 
                                            __( 'Time', 'vc_cfb' )                                                        => 'time', 
                                            __( 'Url', 'vc_cfb' )                                                         => 'url', 
                                            __( 'Month', 'vc_cfb' )                                                       => 'month', 
                                            __( 'Week', 'vc_cfb' )                                                        => 'week', 
                                          ),
                "description"   =>  __( 'Select content type of field.', 'vc_cfb' ),
                "group"         =>  __( 'General', 'vc_cfb' )
              ),
              'placeholder',
              'required',
              'maxlength',
              'tab',
              'autocomplete',
              'autofocus',
              'disabled',
              'readonly',
              'default',
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Max', 'vc_cfb' ),
                "param_name"    =>  "max",
                "is_html5"      =>  true,
                "value"         =>  '',
                "description"   =>  __( 'Specifies the maximum value for an element.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'input_type', 'value' => array( 'number', 'date', 'range', 'datetime', 'datetime-local', 'month', 'time', 'week' ) ),
                "group"         =>  __( 'Content', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Min', 'vc_cfb' ),
                "param_name"    =>  "min",
                "is_html5"      =>  true,
                "value"         =>  '',
                "description"   =>  __( 'Specifies a minimum value for an element.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'input_type', 'value' => array( 'number', 'date', 'range', 'datetime', 'datetime-local', 'month', 'time', 'week' ) ),
                "group"         =>  __( 'Content', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Step', 'vc_cfb' ),
                "is_html5"      =>  true,
                "param_name"    =>  "step",
                "value"         =>  '',
                "description"   =>  __( 'Specifies the legal number intervals for an input field.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'input_type', 'value' => array( 'number', 'range', 'date', 'datetime', 'datetime-local', 'month', 'time', 'week' ) ),
                "group"         =>  __( 'Content', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Pattern for validation', 'vc_cfb' ),
                "is_html5"      =>  true,
                "param_name"    =>  "pattern",
                "value"         =>  array( 
                                            __( 'Custom mask', 'vc_cfb' )                                                 => 'custom', 
                                            __( 'ZIP for USA', 'vc_cfb' )                                                 => 'zip_US', 
                                            __( 'ZIP for United Kingdom', 'vc_cfb' )                                      => 'zip_UK', 
                                            __( 'ZIP for Germany', 'vc_cfb' )                                             => 'zip_DE', 
                                            __( 'ZIP for Canada', 'vc_cfb' )                                              => 'zip_CA', 
                                            __( 'ZIP for France', 'vc_cfb' )                                              => 'zip_FR', 
                                            __( 'ZIP for Italy', 'vc_cfb' )                                               => 'zip_IT', 
                                            __( 'ZIP for Australia', 'vc_cfb' )                                           => 'zip_AU', 
                                            __( 'ZIP for Netherlands', 'vc_cfb' )                                         => 'zip_NL', 
                                            __( 'ZIP for Spain', 'vc_cfb' )                                               => 'zip_ES', 
                                            __( 'ZIP for Denmark', 'vc_cfb' )                                             => 'zip_DK', 
                                            __( 'ZIP for Sweden', 'vc_cfb' )                                              => 'zip_SE', 
                                            __( 'ZIP for Belgium', 'vc_cfb' )                                             => 'zip_BE', 
                                            __( 'ZIP for India', 'vc_cfb' )                                               => 'zip_IN', 
                                            __( 'Hex value', 'vc_cfb' )                                                   => 'hex',
                                            __( 'Email', 'vc_cfb' )                                                       => 'email',
                                            __( 'URL', 'vc_cfb' )                                                         => 'url',
                                            __( 'IP', 'vc_cfb' )                                                          => 'ip',
                                            __( 'Social Security Number', 'vc_cfb' )                                      => 'ssn',
                                            __( 'Time in 12-hour format without seconds (hh:mm)', 'vc_cfb' )              => 'time_12_without_ss',
                                            __( 'Time in 12-hour format with seconds (hh:mm:ss)', 'vc_cfb' )              => 'time_12_with_ss',
                                            __( 'Time in 24-hour format with seconds (hh:mm:ss)', 'vc_cfb' )              => 'time_24_with_ss',
                                            __( 'Time in 24-hour format without seconds (hh:mm)', 'vc_cfb' )              => 'time_24_without_ss',
                                            __( 'Latitude', 'vc_cfb' )                                                    => 'lat',
                                            __( 'Longitude', 'vc_cfb' )                                                   => 'lng',
                                          ),
                "description"   =>  __( 'Select pattern for validate data or set custom.', 'vc_cfb' ),
                "group"         =>  __( 'Content', 'vc_cfb' )
              ),
              array(
                "type"          =>  "encoded_text",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textarea_raw_html vc_cfb_hide_field",
                "heading"       =>  __( 'Pattern', 'vc_cfb' ),
                "param_name"    =>  "custom_pattern",
                "value"         =>  '',
                "dependency"    =>  array( 'element' => 'mask', 'value' => 'custom' ),
                "description"   =>  __( 'The pattern attribute specifies a regular expression that the element\'s value is checked against.', 'vc_cfb' ),
                "group"         =>  __( 'Content', 'vc_cfb' )
              ),
              'label_position',
              'label_width',
              'add_mask',
              'mask_template',
              'mask_placeholder',
              'mask_autoclear',
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Size', 'vc_cfb' ),
                "param_name"    =>  "size",
                "value"         =>  '',
                "description"   =>  __( 'The size attribute specifies the visible width, in characters. It can be rewrited on css. If value is empty, then option will be disabled.', 'vc_cfb' ),
                "group"         =>  __( 'Design', 'vc_cfb' )
              ),
              'add_icon',
              'icon_align',
              'icon_type',
              'icon_fa',
              'icon_oi',
              'icon_ti',
              'icon_ei',
              'icon_li',
              'icon_color',
              'id',
              'classes',
            );