<?php
  $params = array( 
              'name',
              'label',
              'placeholder',
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Placement', 'vc_cfb' ),
                "param_name"    =>  "placement",
                "value"         =>  array( __( 'bottom', 'vc_cfb' ) => 'bottom', __( 'top', 'vc_cfb' ) => 'top', __( 'left', 'vc_cfb' ) => 'left', __( 'right', 'vc_cfb' ) => 'right' ),
                "description"   =>  __( 'Popover placement.', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Align', 'vc_cfb' ),
                "param_name"    =>  "align",
                "value"         =>  array( __( 'left', 'vc_cfb' ) => 'left', __( 'right', 'vc_cfb' ) => 'right' ),
                "description"   =>  __( 'Popover arrow align.', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'autoclose',
                'heading'       =>  __( 'Disable autoclose?', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' ),
                "description"   =>  __( 'Auto close when minute is selected.', 'vc_cfb' ),
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'twelvehour',
                'heading'       =>  __( 'Enable twelvehour?', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' ),
                "description"   =>  __( 'Enables twelve hour mode with AM & PM buttons.', 'vc_cfb' ),
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'vibrate',
                'heading'       =>  __( 'Enable vibrate?', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' ),
                "description"   =>  __( 'Vibrate the device when dragging clock hand.', 'vc_cfb' ),
              ),
              'tab',
              'required',
              'autocomplete',
              'autofocus',
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Donetext', 'vc_cfb' ),
                "param_name"    =>  "donetext",
                "value"         =>  __( 'Done', 'vc_cfb' ),
                "description"   =>  __( 'Done button text.', 'vc_cfb' ),
                "group"         =>  __( 'Content', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'autoclose', 'value' => 'true' ),
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Default value', 'vc_cfb' ),
                "param_name"    =>  "default",
                "value"         =>  '',
                "description"   =>  __( 'Default time: <code>now</code> or <code>hh:mm</code> format', 'vc_cfb' ),
                "group"         =>  __( 'Content', 'vc_cfb' )
              ),
              'label_position',
              'label_width',
              'add_icon',
              'icon_align',
              'icon_type',
              'icon_fa',
              'icon_oi',
              'icon_ti',
              'icon_ei',
              'icon_li',
              'icon_color',
              'id',
              'classes',
            );