<?php
  $params = array( 
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Name of form', 'vc_cfb' ),
                "param_name"    =>  "name",
                "value"         =>  '',
                "description"   =>  __( 'This value will be used for system identification your form and must be unique within one form. If you have enabled History mode name must be unique in site. Do not use space. Example: form_1, demo_form', 'vc_cfb' ),
                "group"         =>  __( 'General', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Type of validation', 'vc_cfb' ),
                "param_name"    =>  "validation",
                "value"         =>  array( __( 'Without', 'vc_cfb' ) => 'without', __( 'Server', 'vc_cfb' ) => 'server', __( 'Client + Server', 'vc_cfb' ) => 'all' ),
                "description"   =>  __( 'Client validation is validation available only at browsers. It not uses any jQuery scripts for validation, it use HTML 5.', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'requests_history',
                'heading'       =>  __( 'Enable requests history?', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' ),
                "description"   =>  __( 'Will be added new tab History.', 'vc_cfb' ),
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'resubmit_protected',
                'heading'       =>  __( 'Enable protected from resubmit?', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'requests_history', 'value' => 'true' ),
                "description"   =>  __( 'Based on IP. You can set timeout. Working only if enabled History mode for form.', 'vc_cfb' ),
              ),
              array(
                'type'          =>  'textfield',
                'value'         =>  '120',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'resubmit_protected_time',
                "dependency"    =>  array( 'element' => 'resubmit_protected', 'value' => 'true' ),
                'heading'       =>  __( 'Time before new submit', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' ),
                "description"   =>  __( 'Time in seconds', 'vc_cfb' ),
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'ajax',
                'heading'       =>  __( 'Enable Ajax?', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' ),
                "description"   =>  __( 'When checked opened new style settings on Design tab.', 'vc_cfb' ),
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Enctype', 'vc_cfb' ),
                "param_name"    =>  "enctype",
                "value"         =>  array( 'application/x-www-form-urlencoded' => 'application/x-www-form-urlencoded', 'multipart/form-data' => 'multipart/form-data', 'text/plain' => 'text/plain' ),
                "description"   =>  __( 'The enctype attribute specifies how the form-data should be encoded when submitting it to the server. The enctype attribute can be used only if method="post". If you use uploading files, you should select enctype as <code>multipart/form-data.</code>', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'The position of validation messages', 'vc_cfb' ),
                "param_name"    =>  "validation_position",
                "value"         =>  array( __( 'Before form', 'vc_cfb' ) => 'form', __( 'Before each element', 'vc_cfb' ) => 'field' ),
                "description"   =>  '',
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Action', 'vc_cfb' ),
                "param_name"    =>  "action",
                "value"         =>  '',
                "description"   =>  __( 'You can set custom url for action. For example to other site.<br/>Default value is your current page url.', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Target', 'vc_cfb' ),
                "param_name"    =>  "target",
                "is_html5"      =>  true,
                "value"         =>  array( '_self' => '_self', '_blank' => '_blank', '_parent' => '_parent', '_top' => '_top' ),
                "description"   =>  __( 'The target attribute specifies a name or a keyword that indicates where to display the response that is received after submitting the form.', 'vc_cfb' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'Method for sending data', 'vc_cfb' ),
                "param_name"    =>  "method",
                "value"         =>  array( 'post' => 'post', 'get' => 'get' ),
                "description"   =>  '',
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              array(
                "type"          =>  "dropdown",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_select vc_cfb_hide_field",
                "heading"       =>  __( 'After successfully submitting', 'vc_cfb' ),
                "param_name"    =>  "after_successfully_submitting",
                "value"         =>  array( 'none' => 'none', 'hide' => 'hide', 'redirect to page' => 'redirect' ),
                "description"   =>  '',
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Link for redirect', 'vc_cfb' ),
                "param_name"    =>  "after_successfully_submitting_link",
                "value"         =>  '',
                "description"   =>  '',
                "dependency"    =>  array( 'element' => 'after_successfully_submitting', 'value' => 'redirect' ),
                "group"         =>  __( 'Advanced', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Subject', 'vc_cfb' ),
                "param_name"    =>  "subject",
                "value"         =>  '',
                "description"   =>  '',
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Recipients', 'vc_cfb' ),
                "param_name"    =>  "recipients",
                "value"         =>  '',
                "description"   =>  __( 'List of recipients emails comma separated.', 'vc_cfb' ),
                "group"         =>  __( 'General', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'The name of the sender', 'vc_cfb' ),
                "param_name"    =>  "sender",
                "value"         =>  '',
                "description"   =>  '',
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'The email of the sender', 'vc_cfb' ),
                "param_name"    =>  "sender_email",
                "value"         =>  get_bloginfo( 'admin_email' ),
                "description"   =>  '',
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                'type'          => 'checkbox',
                'value'         =>  'false',
                'class'         => 'vc_cfb_hide_field',
                'param_name'    => 'email_from_subscriber',
                'heading'       => __( 'Use subscriber data for sending email to recipients?', 'vc_cfb' ),
                "description"   =>  'For "Autoreply" email will be used default email settings.',
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Name form field for name subscriber in email', 'vc_cfb' ),
                "param_name"    =>  "email_from_subscriber_name",
                "value"         =>  '',
                "description"   =>  '',
                "dependency"    =>  array( 'element' => 'email_from_subscriber', 'value' => 'true' ),
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Name form field for email subscriber in email', 'vc_cfb' ),
                "param_name"    =>  "email_from_subscriber_email",
                "value"         =>  '',
                "description"   =>  '',
                "dependency"    =>  array( 'element' => 'email_from_subscriber', 'value' => 'true' ),
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Charset', 'vc_cfb' ),
                "param_name"    =>  "charset",
                "value"         =>  'UTF-8',
                "description"   =>  '',
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                'type'          => 'checkbox',
                'value'         =>  'false',
                'class'         => 'vc_cfb_hide_field',
                'param_name'    => 'smtp',
                'heading'       => __( 'Enable sending by SMTP?', 'vc_cfb' ),
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Host', 'vc_cfb' ),
                "param_name"    =>  "smtp_host",
                "value"         =>  'smtp.gmail.com',
                "description"   =>  '',
                "dependency"    =>  array( 'element' => 'smtp', 'value' => 'true' ),
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Port', 'vc_cfb' ),
                "param_name"    =>  "smtp_port",
                "value"         =>  '587',
                "description"   =>  '',
                "dependency"    =>  array( 'element' => 'smtp', 'value' => 'true' ),
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Username', 'vc_cfb' ),
                "param_name"    =>  "smtp_username",
                "value"         =>  '',
                "description"   =>  '',
                "dependency"    =>  array( 'element' => 'smtp', 'value' => 'true' ),
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Password', 'vc_cfb' ),
                "param_name"    =>  "smtp_password",
                "value"         =>  '',
                "description"   =>  '',
                "dependency"    =>  array( 'element' => 'smtp', 'value' => 'true' ),
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'SMTPSecure', 'vc_cfb' ),
                "param_name"    =>  "smtp_secure",
                "value"         =>  'tls',
                "description"   =>  __( 'This settings don\'t uses if value is empty.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'smtp', 'value' => 'true' ),
                "group"         =>  __( 'Mail Settings', 'vc_cfb' )
              ),
              array(
                "type"          =>  "encoded_text",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textarea vc_cfb_hide_field",
                "heading"       =>  '',
                "is_textarea"   =>  true,
                "param_name"    =>  "template",
                "value"         =>  '',
                "description"   =>  __( 'If value empty will be using default template for each elements of form &lt;code&gt;&lt;li&gt;&lt;strong&gt;label&lt;/strong&gt; value&lt;/li&gt;&lt;/code&gt;. For adding value from field you can use structure <code>%name_field%</code>.', 'vc_cfb' ),
                "group"         =>  __( 'Email template', 'vc_cfb' )
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  're',
                'heading'       =>  __( 'Enable auto reply?', 'vc_cfb' ),
                "group"         =>  __( 'Autoreply', 'vc_cfb' ),
                "description"   =>  __( 'If function enable user will receive automatic email.', 'vc_cfb' ),
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Email field name', 'vc_cfb' ),
                "param_name"    =>  "re_email",
                "value"         =>  '',
                "description"   =>  __( 'Set name field with email value for send message.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 're', 'value' => 'true' ),
                "group"         =>  __( 'Autoreply', 'vc_cfb' )
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  're_attachment',
                'heading'       =>  __( 'Include files in email?', 'vc_cfb' ),
                "group"         =>  __( 'Autoreply', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 're', 'value' => 'true' ),
                "description"   =>  '',
              ),
              array(
                "type"          =>  "encoded_text",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textarea vc_cfb_hide_field",
                "heading"       =>  '',
                "is_textarea"   =>  true,
                "param_name"    =>  "re_template",
                "value"         =>  '',
                "dependency"    =>  array( 'element' => 're', 'value' => 'true' ),
                "description"   =>  __( 'If value empty will be using default template for each elements of form &lt;code&gt;&lt;li&gt;&lt;strong&gt;label&lt;/strong&gt; value&lt;/li&gt;&lt;/code&gt;. For adding value from field you can use structure <code>%name_field%</code>.', 'vc_cfb' ),
                "group"         =>  __( 'Autoreply', 'vc_cfb' )
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'requests_history_ip',
                'heading'       =>  __( 'Save user IP?', 'vc_cfb' ),
                "group"         =>  __( 'History', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'requests_history', 'value' => 'true' ),
                "description"   =>  __( 'Value will be received from $_SERVER', 'vc_cfb' ),
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'requests_files',
                'heading'       =>  __( 'Save user Files?', 'vc_cfb' ),
                "group"         =>  __( 'History', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'requests_history', 'value' => 'true' ),
                "description"   =>  __( 'Files will be uploaded to folder on your site.', 'vc_cfb' ),
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'requests_history_os',
                'heading'       =>  __( 'Save user OS?', 'vc_cfb' ),
                "group"         =>  __( 'History', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'requests_history', 'value' => 'true' ),
                "description"   =>  __( 'Value will be received from $_SERVER[\'HTTP_USER_AGENT\']', 'vc_cfb' ),
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'requests_history_browser',
                'heading'       =>  __( 'Save user Browser?', 'vc_cfb' ),
                "group"         =>  __( 'History', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'requests_history', 'value' => 'true' ),
                "description"   =>  __( 'Value will be received from $_SERVER[\'HTTP_USER_AGENT\']', 'vc_cfb' ),
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'requests_history_language',
                'heading'       =>  __( 'Save user Language?', 'vc_cfb' ),
                "group"         =>  __( 'History', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'requests_history', 'value' => 'true' ),
                "description"   =>  __( 'Value will be received from $_SERVER[\'HTTP_ACCEPT_LANGUAGE\']', 'vc_cfb' ),
              ),
              array(
                'type'          =>  'checkbox',
                'value'         =>  'false',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'requests_history_user_agent',
                'heading'       =>  __( 'Save user User Agent?', 'vc_cfb' ),
                "group"         =>  __( 'History', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'requests_history', 'value' => 'true' ),
                "description"   => __( 'Value will be received from $_SERVER[\'HTTP_USER_AGENT\']', 'vc_cfb' ),
              ),
              array(
                'type'          =>  'requests_list',
                'class'         =>  'vc_cfb_hide_field',
                'param_name'    =>  'requests_history_list',
                'heading'       =>  '',
                "group"         =>  __( 'History', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'requests_history', 'value' => 'true' ),
                "description"   =>  __( 'Data in CSV format will be downloaded without files.', 'vc_cfb' ),
              ),
              'id',
              'classes',
              array(
                'type'          =>  'iconpicker',
                'class'         =>  'vc_cfb_hide_field',
                'heading'       =>  __( 'Select loader', 'vc_cfb' ),
                'param_name'    =>  'loader',
                "dependency"    =>  array( 'element' => 'ajax', 'value' => 'true' ),
                'value'         =>  'vc_cfb_animation vc_cfb_animation-circles_line',
                'settings'      =>  array(
                                    'emptyIcon'     =>  false,
                                    'type'          =>  'cfb_loader',
                                    'iconsPerPage'  =>  200,
                                    'hasSearch'     =>  false,
                                    'source'        =>  array( 
                                              array( 'vc_cfb_animation vc_cfb_animation-hourglass'          => 'Hourglass' ), 
                                              array( 'vc_cfb_animation vc_cfb_animation-ring'               => 'Ring' ), 
                                              array( 'vc_cfb_animation vc_cfb_animation-gears'              => 'Gears' ), 
                                              array( 'vc_cfb_animation vc_cfb_animation-loader'             => 'Loader' ),
                                              array( 'vc_cfb_animation vc_cfb_animation-ellipsis'           => 'Ellipsis' ),  
                                              array( 'vc_cfb_animation vc_cfb_animation-gear'               => 'Gear' ),  
                                    ),
                                  ),
                "group"         =>  __( 'Design', 'vc_cfb' )
              ),
              array(
                "type"          =>  "colorpicker",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_colorpicker vc_cfb_hide_field",
                "heading"       =>  __( 'Background color for loader icon', 'vc_cfb' ),
                "param_name"    =>  "loader_background",
                "value"         =>  'rgba(153,153,153,0.49)',
                "description"   =>  '',
                "dependency"    =>  array( 'element' => 'ajax', 'value' => 'true' ),
                "group"         =>  __( 'Design', 'vc_cfb' )
              ),
              'css',
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Success message', 'vc_cfb' ),
                "param_name"    =>  "messages_success",
                "value"         =>  __( 'Your request was successful sent.', 'vc_cfb' ),
                "description"   =>  '',
                "group"         =>  __( 'Notification messages', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Error message', 'vc_cfb' ),
                "param_name"    =>  "messages_warning",
                "value"         =>  __( 'Something going wrong.', 'vc_cfb' ),
                "description"   =>  '',
                "group"         =>  __( 'Notification messages', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Invalid value', 'vc_cfb' ),
                "param_name"    =>  "messages_invalid",
                "value"         =>  __( 'Invalid value for the field %s.', 'vc_cfb' ),
                "description"   =>  __( '<code>%s</code> will be automatically replaced to field title.', 'vc_cfb' ),
                "group"         =>  __( 'Notification messages', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Required field', 'vc_cfb' ),
                "param_name"    =>  "messages_required",
                "value"         =>  __( '%s is required field.', 'vc_cfb' ),
                "description"   =>  __( '<code>%s</code> will be automatically replaced to field title.', 'vc_cfb' ),
                "group"         =>  __( 'Notification messages', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'ReSubmit form', 'vc_cfb' ),
                "param_name"    =>  "messages_resubmit",
                "value"         =>  __( 'You can submit form each %s seconds.', 'vc_cfb' ),
                "dependency"    =>  array( 'element' => 'resubmit_protected', 'value' => 'true' ),
                "description"   =>  __( '<code>%s</code> will be automatically replaced to value from "Time before new submit".<br/><code>%s (2)</code> will be automatically replaced to difference between "Time Last Query" and "Present Time".', 'vc_cfb' ),
                "group"         =>  __( 'Notification messages', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Enter captcha', 'vc_cfb' ),
                "param_name"    =>  "messages_captcha_enter",
                "value"         =>  __( 'Please, enter the code captcha.', 'vc_cfb' ),
                "description"   =>  '',
                "group"         =>  __( 'Notification messages', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Error captcha', 'vc_cfb' ),
                "param_name"    =>  "messages_captcha",
                "value"         =>  __( 'Incorrect captcha code.', 'vc_cfb' ),
                "description"   =>  '',
                "group"         =>  __( 'Notification messages', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'File size', 'vc_cfb' ),
                "param_name"    =>  "messages_file_size",
                "value"         =>  __( 'Invalid file size.', 'vc_cfb' ),
                "description"   =>  '',
                "group"         =>  __( 'Notification messages', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'File accept', 'vc_cfb' ),
                "param_name"    =>  "messages_file_accept",
                "value"         =>  __( 'Invalid file format.', 'vc_cfb' ),
                "description"   =>  '',
                "group"         =>  __( 'Notification messages', 'vc_cfb' )
              ),
              array(
                "type"          =>  "textfield",
                "holder"        =>  "div",
                "class"         =>  "vc_cfb_field_textfield vc_cfb_hide_field",
                "heading"       =>  __( 'Popup text', 'vc_cfb' ),
                "param_name"    =>  "popup",
                "value"         =>  __( 'You are sure?', 'vc_cfb' ),
                "description"   =>  __( 'Text message for popup, it will be showed after click to submit. If value is empty, popup will be disabled.', 'vc_cfb' ),
                "group"         =>  __( 'Notification messages', 'vc_cfb' )
              ),
            );